### ISSUE TITLE
As an engineer I want to be able to change Locamation privates to configure an IED

### ISSUE THREAD

**Issue by randy993** [com-pas/compas-open-scd#104]
As an engineer I want to be able to change Locamation privates to configure an IED

SO I can configure the Locamation VMU with CoMPAS

 

Background:
Locamation uses privates in the IED configuration files to configure some Locamation specific parameters. Therefore we need an extension in CoMPAS so a user can adjust these parameters. 

This needs to be supported to support the Locamation VMU:
Namespace:

xmlns:ext="https://www.locamation.com/61850/VMU/SCL"

Extensions to the LN’s:

				<LN inst="2" lnClass="TCTR" lnType="TCTR_LCMTN" prefix="I01B">
					<Private type="LCMTN_VMU_SENSOR">
						<ext:P type="IDENTIFIER"/>
						<ext:P type="CHANNEL"/>
						<ext:P type="TRANSFORM-PRIMARY"/>
						<ext:P type="TRANSFORM-SECONDARY"/>
					</Private>

This will be proably removed and replace by a IEC61850 concept:
						<ext:P type="TRANSFORM-PRIMARY"/>
						<ext:P type="TRANSFORM-SE

**Comment by Sander3003** [comment]
For Locamation (Edwin) do you still want to add these types?
<ext:P type="TRANSFORM-PRIMARY"/>
<ext:P type="TRANSFORM-SE

Can you check the story?

**Comment by EFMH** [comment]
The namespace to be checked in the <SCL> tag shall be:

<SCL ... xmlns:lcmtn_ext="https://www.locamation.com/61850/VMU/SCL">

Furthermore the <Private> section to look for is:

<Private type="LCMTN_VMU_SENSOR">
	<lcmtn_ext:P type="VERSION">1</lcmtn_ext:P>
	<lcmtn_ext:P type="IDENTIFIER">0.0.0</lcmtn_ext:P>
	<lcmtn_ext:P type="CHANNEL">0</lcmtn_ext:P>
	<lcmtn_ext:P type="TRANSFORM-PRIMARY">1000</lcmtn_ext:P>
	<lcmtn_ext:P type="TRANSFORM-SECONDARY">1</lcmtn_ext:P>
</Private>

where the Private.type("LCMTN_VMU_SENSOR") can be considered to be constant and the Private.lcmtn_ext:P.type("VERSION") will always be present. The version value is an identifier for the rest of the structure.
The TRANSFORM-PRIMARY and TRANSFORM-SECONDARY are currently subject to investigation and might be modeled in the IED's data model in the future. In that case the <Private> structure will change and the VERSION number will be increased.

**Comment by Sander3003** [comment]
@EFMH do you have an Locamation XSD for this?

**Comment by Sander3003** [comment]
Todo;
Are these extensions described in the XSD or NSD files?
Can we build a service to that loads these XSD's and/or NSD files to find the private fields?

**Comment by randy993** [comment]
@EFMH Will create the XSD for the validation of the private element.

**Comment by Sander3003** [comment]
According to @JakobVogelsang a lot of private fields can be replaced by standard IEC61850 fields. @EFMH can you add a description of the private fields and motivation why a private field is necessary in this case?

**Comment by randy993** [comment]
As discussed with @dlabordus, @Flurb and @Sander3003 , goto for now is a menu plug-in which can edit the Locamation privates per IED. 

**ToDo**
- Create Locamation plug-in in the CoMPAS menu
- VMU Editor should pop up when the user clicks the plug-in
-- Selector for Locamation IEDs should be shown to the user, based up `IED` elements containing the parameter `manufacturer="Locamation B.V."`
-- For each `LN` with a private element of the type `<Private type="LCMTN_VMU_SENSOR">` the Channel, Identifier, Transform-primary and Transform-secondary should be shown
-- The user can edit the values and save them in the following way 
```XML
<Private type="LCMTN_VMU_SENSOR">
    <lcmtn_ext:P type="VERSION">1</lcmtn_ext:P>
    <lcmtn_ext:P type="IDENTIFIER">0.0.0</lcmtn_ext:P>
    <lcmtn_ext:P type="CHANNEL">0</lcmtn_ext:P>
    <lcmtn_ext:P type="TRANSFORM-PRIMARY">1000</lcmtn_ext:P>
    <lcmtn_ext:P type="TRANSFORM-SECONDARY">1</lcmtn_ext:P>
</Private>
```

**Questions**
- What, where and how will we validate the user input? In the front-end through the widget? By using an XSD?

**Comment by dlabordus** [comment]
Simple validation can be done in the Wizard, like required and maskers (regexps).
OpenSCD currently only validates against the SCL XSD. There is no future to extend this.
Also I think you don't want the XSD depend on the SCL XSD, because you need a import the file in these cases.

Maybe look at creating a OCL for Locamation for the more complex checks. 
And use that in the Validator Service where we are now looking into.

**Comment by Sander3003** [comment]
I agree wit the idea's of @dlabordus

**Comment by randy993** [comment]
Seems fine, in that case @EFMH does not have to deliver the XSD anymore. But is it possible to deliver a set of restrictions for all fields we can implement in the plug-in?

**Comment by EFMH** [comment]
> As discussed with @dlabordus, @Flurb and @Sander3003 , goto for now is a menu plug-in which can edit the Locamation privates per IED.
> 
> **ToDo**
> 
> * Create Locamation plug-in in the CoMPAS menu
> * VMU Editor should pop up when the user clicks the plug-in
>   -- Selector for Locamation IEDs should be shown to the user, based on `IED` elements containing the parameter `manufacturer="Locamation B.V."`
>   -- For each `LN` with a private element of the type `<Private type="LCMTN_VMU_SENSOR">` the Channel, Identifier, Transform-primary and Transform-secondary should be shown
>   -- The user can edit the values and save them in the following way
> 
> ```
> <Private type="LCMTN_VMU_SENSOR">
>     <lcmtn_ext:P type="IDENTIFIER">0.0.0</lcmtn_ext:P>
>     <lcmtn_ext:P type="CHANNEL">0</lcmtn_ext:P>
>     <lcmtn_ext:P type="TRANSFORM-PRIMARY">1000</lcmtn_ext:P>
>     <lcmtn_ext:P type="TRANSFORM-SECONDARY">1</lcmtn_ext:P>
> </Private>
> ```
> 
> **Questions**
> 
> * What, where and how will we validate the user input? In the front-end through the widget? By using an XSD?

**Comment by EFMH** [comment]
Sorry, I pressed the wrong button and accidently closed the issue.
I want to comment on Randy's comment of 4 days ago. I general I agree with his proposal. Please be aware that you use the wrong structure of the private that Locamation uses. I provided the structure on december 22.
Further, to validate the input of the variables in the private section, I can give types and valid ranges. 
Last week we discussed the need for 'TRANSFORM-PRIMARY' and 'TRANSFORM-SECONDARY' in this private section. For now, this is how we define the ratio, but this will most likely change by using a data object in the IEC61850 standard.

**Comment by Sander3003** [comment]
@EFMH can you upload/show the correct structure here to prevent any confusion?

**Comment by EFMH** [comment]
```XML
<Private type="LCMTN_VMU_SENSOR">
    <lcmtn_ext:P type="VERSION">1</lcmtn_ext:P>
    <lcmtn_ext:P type="IDENTIFIER">0.0.0</lcmtn_ext:P>
    <lcmtn_ext:P type="CHANNEL">0</lcmtn_ext:P>
    <lcmtn_ext:P type="TRANSFORM-PRIMARY">1000</lcmtn_ext:P>
    <lcmtn_ext:P type="TRANSFORM-SECONDARY">1</lcmtn_ext:P>
</Private>
```

Above an example of the current private structure. The structure can be identified by the type 'LCMTN_VMU_SENSOR'.
- VERSION, this is the version number of the private structure 'LCMTN_VMU_SENSOR'. In case the structure changes, this number will be incremented.
- IDENTIFIER, this is the address of the sensor. The address is constructed of 3 numbers, separated by dots. The range of each number is 0-255.
- CHANNEL, this is the channel number on the sensor. Values for the current sensor range from 0 - 6, for the voltage sensor 0-2.
- TRANSFORM-PRIMARY, this is the nominator of the ratio of the measement transformer.
- TRANSFORM-SECONDARY, this is the denominator of the ratio of the measement transformer.

**Comment by dlabordus** [comment]
Hi @EFMH,

I have some question during building the plugin.

Question about, "CHANNEL, this is the channel number on the sensor. Values for the current sensor range from 0 - 6, for the voltage sensor 0-2.", What's the difference between current sensor and voltage sensor? This is the first time this is mentioned.

And looking at the video of the meeting between you, Randy and Sander, I see that in the current web interface you edit the CIM and VIM values all at once for a single IED/Logical Device, but that means updating 8 Logical Nodes, correct?
- Is this also the way it should go in OpenSCD in the Plugin?
- If so what are the rules to know which 8 logical nodes to select? 
  I see some pattern 
  - <LN prefix="I01(A|B|C\N)" lnClass="TCTR" inst="1" lnType="TCTR_LCMTN"> (4 times)
  - <LN prefix="V01(A|B|C\N)" lnClass="TVTR" inst="1" lnType="TVTR_LCMTN"> (and 4 times)
- For which the Transform-Primary/Secondary are all the same? First Logical Node will be leading to show on screen?
- And to be sure, the "SUM" is used in the logical node I01N and V01N? The others have CHANNEL.

I have got 2 files from Randy (SCD and ICD), but these contain the initial structure describe here, not the one mentioned in the last comments. Can some updated examples be supplied?

**Comment by EFMH** [comment]
@dlabordus, I fixed 2 typos in my post. The current sensors have channels ranging from 0-5, not 0-6. I'll explain in the meeting later today.
