### ISSUE TITLE
Automatically load NSDOC Files in OpenSCD from backend (SCL Validator)

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#120]
To make live easier for CoMPAS User the NSDOC Files will automatically be loaded from the Backend Service (SCL Validator).

- Make a call to '/nsdoc' to retrieve the list of available NSDOC Files in the backend.
- For every entry in the list check if the checksum is changed, if so retrieve the NSDOC File and fire the load event to make OpenSCD load the file. Also store the checksum in the local storage for later use.
- Remove OpenSCD upload button and trash bins, change title to NSDoc files (-> OpenSCD)
![image](https://user-images.githubusercontent.com/47896624/158533376-1ee32fb8-af46-485e-80f7-b408ddc49486.png)

Just like retrieving the User Info from the backend make a call to load the NSDOC Files when the CoMPAS Settings plugin is loaded.

First the issue https://github.com/com-pas/compas-scl-validator/issues/13 needs to be build, before this issue can be picked up.
After this issue the next issue (https://github.com/com-pas/compas-deployment/issues/53) can be done to make everything work together.

**Comment by randy993** [comment]
I think we should hide this part as well. Adding a boolean to enable/disable the loading of the NSDOC files would be nice, this way the user can still decide wether to load the NSDOC files or not.
![image](https://user-images.githubusercontent.com/47896624/158533376-1ee32fb8-af46-485e-80f7-b408ddc49486.png)

**Comment by dlabordus** [comment]
Didn't remove the trash bin icon, only the manual upload button.
This way we can easy force reloading the NSDoc File if that's needed for some reason.
