### ISSUE TITLE
Idea: graphical compare of SCL changes

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#140]
As an engineer
I want to see a graphical compare of SCL files
So I can easily spot changes

Inspiration: https://winmerge.org/

Open questions:
What SCL parts should be compared? Only the substaiton editor/window?

**Comment by JakobVogelsang** [comment]
OpenSCD uses a web component named `ace-editor`. This is the thing that shows the plane code in the wizards for various elements. There is a wrapper for this editor called [ace-diff](https://ace-diff.github.io/ace-diff/) that might be used for this used case. 

Depending on the implementation of Issue [836](https://github.com/openscd/open-scd/issues/836) we can add on with this other type of view :)

**Comment by JakobVogelsang** [comment]
@Sander3003 is this issue still valid or did we cover that with the plain compare window
