### ISSUE TITLE
Make the compare function more clear for users

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#141]
As an engineer
Want to to have clear what the window shows
So I can understand the differences better

**Requirements**
Show all types of differences possible in an SCL file:
- attribute(A) missing in current project (ours) compared to the other (theirs)
- attribute(A) missing in theirs compared to ours
- attribute(A) present in both ours and theirs but differ
- innerText(T) missing in ours compared to theirs
- innerText(T) missing in theirs compared to ours
- innerText(T) present in both ours and theirs but differs
- element(E) in missing in ours compared to theirs
- element(E) missing in theirs compared to ours
- use identity string from open-scd foundation in secondary string to show the element's location
- allow to user define the titles

TODO: change T to C

**Out of scope**
- filtering of the diff 
- editing/merging of any of the diff

**Mockup**
![mock_diff_with_example excalidraw](https://user-images.githubusercontent.com/66802940/177934159-86b07041-97c1-404c-b653-c08ad5ed27f6.png)

**Additional Information**
I would give it a shot with two synced list. I think this is just some CSS that allows us to do so. (see [stackoverflow discussion](https://stackoverflow.com/questions/62992858/css-having-two-lists-sync-their-vertical-scroll-while-allowing-one-to-scroll-ho)) 

Old way of comparison:
![image](https://user-images.githubusercontent.com/7427358/162938201-cf769ac0-bf43-4e4f-a2f3-c50b8b535a48.png)

**Comment by Sander3003** [comment]
Suggestion: to witch old version to new version

**Comment by JakobVogelsang** [comment]
I would give it a shot with two synced list. I think this is just some CSS that allows us to do so. (see [stackoverflow discussion](https://stackoverflow.com/questions/62992858/css-having-two-lists-sync-their-vertical-scroll-while-allowing-one-to-scroll-ho)) If this is possible, then we could have something like this:
![mock_diff_with_example excalidraw](https://user-images.githubusercontent.com/66802940/177558561-10441e4b-d5e6-45d4-a4c2-999b4e41d7d0.png)

What do you think?

! The search bar should be an extra issue, I think :)

**Comment by JakobVogelsang** [comment]
Moved issue to OpenSCD
https://github.com/openscd/open-scd/issues/919
