### ISSUE TITLE
Add version to an existing SCL file in CoMPAS

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#143]
As an engineer
I want to the current opened SCL File as a new version file to an existing SCL file in CoMPAS
So I can "overwrite" an existing configuration and don't need to create new files and remove old/unsed ones.

Background:
Add a new menu item 'Save as new version'. The next steps will happen:
- First show the list of types. The engineer select the type of SCL File
![image](https://user-images.githubusercontent.com/1453032/164388776-e60a6eaa-e202-4272-8de3-f5c0dfa27fb6.png)
- Next show the existing SCL File for the selected type. The engineer can now select the SCL File to which a new version will be added
![image](https://user-images.githubusercontent.com/1453032/164388869-2d969691-81af-401e-b27a-d0e1b74e6c7d.png)
- The final step is to select what type of change the new version will become. Also comments can be added
![image](https://user-images.githubusercontent.com/1453032/164389277-00d2ace8-9a4e-4898-ab3e-7054b11810b7.png)
- Final step is to save the current SCL File as new version to the selected SCL File from step 2.

**Comment by dlabordus** [comment]
Original screen-capture from Sander
![image](https://user-images.githubusercontent.com/7427358/162949159-335ab32e-7d00-4153-bc28-8090dd43fc83.png)
