### ISSUE TITLE
Use new Compare Window for comparing CoMPAS Version

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#193]
**Is your feature request related to a problem? Please describe.**
For the Compare IED there is a new Compare Dialog, which is more clear.
The compare function of CoMPAS Versions Editor is still using the old logic.
This should be replaced with the logic for the new Compare Dialog.

**Describe the solution you'd like**
Replace the old compare dialog with the new compare dialog.

**Additional information**
None

**Comment by Sander3003** [comment]
Build a full compare for full SCL files:

![image](https://user-images.githubusercontent.com/7427358/194057192-6229c425-d19c-4cd4-987b-96f5b415321e.png)
