### ISSUE TITLE
Broken Save as to local file

### ISSUE THREAD

**Issue by JakobVogelsang** [com-pas/compas-open-scd#194]
**Describe the bug**
Save as plugin does not export files to locally only to the database

**To Reproduce**
1. Open some file
2. Go to `Save as` plugin
3. Click save to file
4. Nothing happens

**Additional context**
Browser log says `removeChild on Node ...`

**Comment by dlabordus** [comment]
Also found the bug Thursday, should be fixed already.

I got the error when saving file to CoMPAS caused a error.
And next try to save it again.
Because the labels are already replaced in the document, the list should have been reset even if save fails.
