### ISSUE TITLE
Document monitoring setup using Elastic’s RUM Agent

### ISSUE THREAD

**Issue by juancho0202** [com-pas/compas-open-scd#216]
**Description**
As a user of CoMPAS-OpenSCD I want to count on documentation to use as reference for setting up Elastic Real User Monitoring (RUM) in my cloud environment

Acceptance criteria:
High-level proces  (including the replacement proces and files involved)
Library used 
Reference to the Elestic documentation

Where to put it: CoMPAS deployment readme.md

**Comment by Sander3003** [comment]
https://github.com/com-pas/contributing/blob/main/docs/MONITORING.md
