### ISSUE TITLE
Documentation for Compass Plugins and back end

### ISSUE THREAD

**Issue by gillerman** [com-pas/compas-open-scd#225]
Is there documentation about the functionality provided by the CoMPAS Backend Service and other CoMPAS plugins?

**Comment by gillerman** [comment]
Found this:https://www.lfenergy.org/learn-the-basics-of-compas-with-these-free-tutorials/.

**Comment by Sander3003** [comment]
Great, technical documentation can be found in the relevant repository. Please re-open if needed.
