### ISSUE TITLE
IEC 61850 Client/OPC Server

### ISSUE THREAD

**Issue by gillerman** [com-pas/compas-open-scd#226]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. As a user of OpenSCD I want to ...

**Describe the solution you'd like**

**Requirements**
What are the minimal requirements you need to have for this feature wish

**Suggestions for a specific user interaction**
Have a specific UI gesture in mind? If you want to discuss this first, please provide your suggestion in the discussions field.

**Additional information**
For further reading including e.g parts of IEC 61850, Tissues or other sources that triggered your feature wish

**Test Files**
If possible provide a file that can be used to test the feature and explain what is the outcome of the test with the test file

**Comment by gillerman** [comment]
Found this: https://www.youtube.com/watch?v=WVOCXx6Cdn8 about FledgePower Gateway

**Comment by Sander3003** [comment]
Thanks for reaching out @gillerman ! LF energy CoMPAS is focused on (static) 61850 configuration, if you want to add OPC parameters to 61850 SCL, CoMPAS is a good place to start (with a plug-in). FledgePower can to used for the realtime aspects. Feel free to close the issue if your question is answered.

**Comment by Sander3003** [comment]
Feel free to re-open if needed.
