### ISSUE TITLE
Generate a CSV file containing 104 information from the IEC 61850 SCL file

### ISSUE THREAD

**Issue by DavoodSooran** [com-pas/compas-open-scd#334]
**Is your feature request related to a problem? Please describe.**
As a user of CoMPAS, I would like to be able to to export a CSV file from the IEC 61850 SCL file, containing relevant IEC 104 addresses and associated information. The outlined process in the like below explains how to export a CSV file from the SCL file and details the expected outcome and information within the CSV file.

![image](https://github.com/user-attachments/assets/c42660d8-81a6-469a-a34e-6c9bdc6a395b)
![image](https://github.com/user-attachments/assets/1512428f-fbb1-46c2-b51e-51957d934adc)
![image](https://github.com/user-attachments/assets/9ab9d452-03a6-45dc-b524-9673af4237a6)
![image](https://github.com/user-attachments/assets/758a292d-7f88-4e7d-a7d6-9bc769493eca)
![image](https://github.com/user-attachments/assets/59e0c340-9207-4229-81b1-80c9eb5e04d0)
![image](https://github.com/user-attachments/assets/de9b5fa8-9227-4a89-a86b-094af8d66b38)
![image](https://github.com/user-attachments/assets/2e6bf9dd-110a-4df8-994c-9a140647ebc4)

**Comment by DavoodSooran** [comment]
@Sander3003 I made this ticket for Exporting CSV file feature.

**Comment by DavoodSooran** [comment]
@Sander3003 I just updated the pictures here. I have also sent a request for emoving the picture by the URL that you shared. Now I have to wait for a reply from them.

**Comment by Sander3003** [comment]
It is fixed, thanks @DavoodSooran!
