### ISSUE TITLE
Spike: Publisher plug-in As used by OpenSCD Transpower Distribution

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#338]
Spike to dive into the plug-in
What is needed to get plug-in running into CoMPAS/OpenSCD?
e.g. depencendies conflicts, API incompatibilities etc

The plug-in can be found here:
https://danyill.github.io/scl-editor/

Acceptance criteria:
Identify and create stories that need to be done to get the Plublisher plug-in into CoMPAS

**Comment by clepski** [comment]
The list of stuff which has to be done can be found here https://github.com/openscd/open-scd/issues/1596
