### ISSUE TITLE
Implement Error Handling for Called to Webservices (SCL Data Service/CIM Mapping)

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#47]
As a user
I want better feedback when a Webservice call fails
So that I know the call went wrong

Background:
The fetch call to a Webservice can fail and return something else then 200 OK.
So we need to handle the catch and investigate how we can do that nicely.
Error message can be written to the OpenSCD Logging to be displayed to the user.

Also HTTP Error Code 401 and 403 can be handle generic, because we need to force a reload of OpenSCD.
Maybe setting the window.src to "/" again will reload the web application forcing the user back to the logging again.

Acceptance:
- Error Message is shown when Webservice call fails. For instance stopping the BaseX Docker instance, the SCL Data Service will return a 500 error.

**Comment by Sander3003** [comment]
Find a way to force login after a time-out (401).
