### ISSUE TITLE
Delete a SCL (Version) from CoMPAS

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#51]
As a user
I want to be able to remove a specific version of all versions of a SCL from CoMPAS
So that old version or SCL entries can be removed

Background:
On a History tab the different versions that are found in CoMPAS are displayed.
The idea is to add a delete (trash can) button at each row to remove a specific version.
And also some Delete All button to remove the whole SCL from CoMPAS.

**Comment by Sander3003** [comment]
It would be nice if buttons are grey-out if the user has not efficiënt rights.
