### ISSUE TITLE
Full Compare - Group SCL diffs based on SCL sections

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#57]
As an engineer
I want see all SCL diffs as list (one view) grouped by section (Substation,Voltage etc) with the attributes
So I have an faster overview of SCL file differences

Background:
This will replace the current compare function. Also show all child elements and attributed from deleted and added attributes.

**Comment by Flurb** [comment]
Maybe OpenSCD already has some functionality which can be reused:
https://github.com/openscd/open-scd/blob/main/src/wizards.ts

**Comment by Sander3003** [comment]
https://github.com/openscd/open-scd/issues/349
