### ISSUE TITLE
Create Unittest with Mocking the Fetch Call to the SCL Data Service

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-open-scd#6]
As a developer
I want to improve the coverage of the Compas Unittests
So that in the future the change of breaking the software decreases

To make some of the test for the Compas component useful we need to mock the fetch call that is done to the SCL Data Service. Already tried some solutions, but failed. Need some more investigation to be done. 

- fetch-mock is a nice one. 
- Sinon needs a extends for this to work, but doesn't seem to be working.

**Comment by Sander3003** [comment]
This to be checked by @dlabordus
