### ISSUE TITLE
Make Service Worker work correctly regarding 401/403 HTTP Errors

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#90]
As a user
I want OpenSCD to work fast and being cached locally, but not have any trouble when i'm no longer logged in
So that loading OpenSCD doesn't need to be done every time

Background:
There is now a issue regarding the Service Worker and the situation the user is no longer logged in.
Sometimes OpenSCD keeps on working, but there are also cases that a blank screen is shown.
Looking at the logging in the browser we can see that the Service Worker tries to retrieve files, but can't because the user is no longer logged in.
See if we can optimize the retrieval of resources by the Service Worker by redirecting the user back to the home page to login after a 401/403 error is returned.

**Comment by dlabordus** [comment]
Change the configuration of the Service Worker. Exclude the index.html, this will cause the browser to always go to the browser after reload. The configuration is now a more white list also excluding the CoMPAS Backend services.
